#!/bin/bash
# Waits for Intel Swarm prep to complete, then runs full orchestration
LOG="/home/yeoel/.openclaw/workspace/intel_swarm/scratch/delayed_orch.log"
exec >> "$LOG" 2>&1
echo "[$(date)] Orchestrator watching for prep completion..."

# Wait for prep to create orchestrator file
while true; do
    FILE=$(ls -t /home/yeoel/.openclaw/workspace/intel_swarm/scratch/orchestrator_20260415_*.txt 2>/dev/null | head -1)
    if [ -n "$FILE" ] && [ ! -f "/home/yeoel/.openclaw/workspace/intel_swarm/results/master_20260415_*.json" ]; then
        echo "[$(date)] Found: $FILE"
        break
    fi
    sleep 30
done

cd /home/yeoel/.openclaw/workspace
python3 << 'PYEOF'
import json, subprocess, sys
from pathlib import Path
from datetime import datetime

TS = "20260415_1834"
RESULTS = Path("/home/yeoel/.openclaw/workspace/intel_swarm/results")
WORKSPACE = Path("/home/yeoel/.openclaw/workspace")
SGT = datetime.now().strftime("%Y-%m-%d %I:%M %p SGT")
UTC = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

# Read all 3 domain reports
domains = {}
for d in ['geopolitics','finance','climate']:
    fp = RESULTS / f"{d}_{TS}.json"
    if not fp.exists():
        print(f"Missing {d}")
        sys.exit(1)
    with open(fp) as f:
        domains[d] = json.load(f)

# Build alerts summary
all_insights = []
for d, data in domains.items():
    for i in data.get('insights', []):
        i['domain'] = d
        all_insights.append(i)

alerts = {'critical': [], 'high': [], 'medium': [], 'low': []}
for i in all_insights:
    lvl = i.get('alert_level', 'LOW').lower()
    if lvl in alerts:
        alerts[lvl].append(i['headline'])

level_order = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW']
top = sorted(all_insights, key=lambda x: level_order.index(x.get('alert_level','LOW')))[:20]
patterns = list(set(sum([d.get('patterns',[]) for d in domains.values()],[])))
blinds = list(set(sum([d.get('blind_spots',[]) for d in domains.values()],[])))

key_themes = [{"theme": t['headline'][:80], "description": t.get('summary','')[:200], "supporting_evidence": [t.get('source_names',[''])[0]], "confidence": t.get('alert_level','MEDIUM')} for t in top[:5]]

alpha = [{"angle": "Hormuz ceasefire arbitrage", "rationale": "Diplomatic talks vs military reality disconnect in Iran blockade", "timeframe": "SHORT", "risk": "HIGH"}]

master = {
    "report_type": "MASTER_INTELLIGENCE_REPORT",
    "timestamp": TS,
    "sgt_time": SGT,
    "utc_time": UTC,
    "executive_summary": f"Intelligence summary {SGT}. Key: {top[0]['headline'] if top else 'See full report'}.",
    "key_themes": key_themes,
    "alpha_opportunities": alpha,
    "cross_domain_patterns": patterns[:5],
    "blind_spots": blinds[:5],
    "reference_index": [],
    "alerts_summary": alerts
}

master_path = RESULTS / f"master_{TS}.json"
with open(master_path, 'w') as f:
    json.dump(master, f, indent=2)
print(f"Master saved: {len(alerts['critical'])} CRIT, {len(alerts['high'])} HIGH")

# Markdown
md = f"""---
title: Intelligence Report — {SGT}
date: {TS}
type: intelligence-report
tags: [intel, daily-brief, world-monitor]
---

# 🧠 Master Intelligence Report
**Generated:** {SGT} | {UTC}

## Executive Summary
{master['executive_summary']}

## Key Themes
"""
for t in key_themes:
    md += f"### {t['theme']}\n{t['description']}\n\n"

md += "## Alerts Summary\n"
for lvl, items in alerts.items():
    if items:
        emoji = {'critical':'🔴','high':'🟠','medium':'🟡','low':'🟢'}.get(lvl,'⚪')
        md += f"### {emoji} {lvl.upper()} ({len(items)})\n"
        for h in items: md += f"- {h}\n"
        md += "\n"

md += f"\n*Generated by yoyoclaw Intelligence Swarm · {UTC}*\n"

md_path = RESULTS.parent / "reports" / f"intel_report_{TS}.md"
md_path.parent.mkdir(parents=True, exist_ok=True)
md_path.write_text(md)
print(f"Markdown saved: {md_path.name}")

# Obsidian
import shutil
dest = Path.home() / "Documents/openclaw/Worldnews/Daily Intel" / f"Intel-Report-{TS}.md"
dest.parent.mkdir(parents=True, exist_ok=True)
shutil.copy2(md_path, dest)
print("Obsidian saved")

# GitHub
subprocess.run(["git","add",str(md_path),str(master_path)], cwd=WORKSPACE)
subprocess.run(["git","commit","-m",f"Intel Report {TS}"], cwd=WORKSPACE)
result = subprocess.run(["git","push","origin","main"], cwd=WORKSPACE, capture_output=True, text=True)
print(f"GitHub: {result.returncode}")
PYEOF
echo "[$(date)] Orchestration complete"
